#
# This workflow calls the main distribution pipeline from DuckDB to build, test and (optionally) release the extension
#
name: Main Extension Distribution Pipeline
on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/main' || github.sha }}
  cancel-in-progress: true

jobs:
  duckdb-stable-build:
    name: Build extension binaries
    uses: duckdb/extension-ci-tools/.github/workflows/_extension_distribution.yml@v1.5-variegata
    with:
      extension_name: iceberg
      duckdb_version: 27f138a712dd12d412ca4aa6837726c2a3c5bc12
      ci_tools_version: v1.5-variegata
      exclude_archs: 'windows_amd64_mingw'
      extra_toolchains: 'python3'
      build_type: 'debug'

  duckdb-stable-deploy:
    name: Deploy extension binaries
    needs: duckdb-stable-build
    uses: duckdb/extension-ci-tools/.github/workflows/_extension_deploy.yml@v1.5-variegata
    secrets: inherit
    with:
      extension_name: iceberg
      duckdb_version: 27f138a712dd12d412ca4aa6837726c2a3c5bc12
      ci_tools_version: v1.5-variegata
      exclude_archs: 'windows_amd64_mingw'
      deploy_latest: ${{ startsWith(github.ref, 'refs/heads/v') || github.ref == 'refs/heads/main' }}
      deploy_versioned: ${{ startsWith(github.ref, 'refs/heads/v') || github.ref == 'refs/heads/main' }}
